"""Mining State Machine Enums and Priorities for Graal Mining Macro."""

from enum import Enum, auto


class MiningState(Enum):
    # System / Idle states
    IDLE = "IDLE"
    WINDOW_NOT_FOUND = "WINDOW_NOT_FOUND"
    INITIALIZING = "INITIALIZING"
    CHECKING_GAME = "CHECKING_GAME"

    # Observation state
    OBSERVATION = "OBSERVATION"

    # Normal mining loop states
    CHECKING_DRILL = "CHECKING_DRILL"
    EQUIPPING_DRILL = "EQUIPPING_DRILL"
    SEARCHING_FOR_PLAYER = "SEARCHING_FOR_PLAYER"
    SEARCHING_FOR_TARGET = "SEARCHING_FOR_TARGET"
    APPROACHING_TARGET = "APPROACHING_TARGET"
    POSITIONING = "POSITIONING"
    VERIFYING_POSITION = "VERIFYING_POSITION"
    MINING = "MINING"
    VERIFYING_MINING = "VERIFYING_MINING"
    TARGET_COMPLETED = "TARGET_COMPLETED"
    SEARCHING_NEXT_TARGET = "SEARCHING_NEXT_TARGET"

    # Interrupt / Recovery states
    SPIDER_DETECTED = "SPIDER_DETECTED"
    COMBAT = "COMBAT"
    VERIFYING_COMBAT = "VERIFYING_COMBAT"

    PLAYER_DRAGGED_AWAY = "PLAYER_DRAGGED_AWAY"
    REACQUIRING_WALL = "REACQUIRING_WALL"

    NOTHING_TO_MINE = "NOTHING_TO_MINE"
    WAITING_COOLDOWN = "WAITING_COOLDOWN"

    MINE_COLLAPSE_DETECTED = "MINE_COLLAPSE_DETECTED"
    EXITING_MINE = "EXITING_MINE"
    VERIFYING_SURFACE = "VERIFYING_SURFACE"
    REENTERING_MINE = "REENTERING_MINE"
    VERIFYING_MINE_ENTRY = "VERIFYING_MINE_ENTRY"

    BATTERY_EMPTY = "BATTERY_EMPTY"
    GOING_TO_BATTERY_LOCATION = "GOING_TO_BATTERY_LOCATION"
    BUYING_BATTERY = "BUYING_BATTERY"
    VERIFYING_BATTERY = "VERIFYING_BATTERY"
    RETURNING_TO_MINE = "RETURNING_TO_MINE"

    # Safety / Control states
    PAUSED = "PAUSED"
    ERROR = "ERROR"
    PERCEPTION_ERROR = "PERCEPTION_ERROR"
    STOPPED = "STOPPED"
    EMERGENCY_STOP = "EMERGENCY_STOP"


STATE_PRIORITY = {
    MiningState.EMERGENCY_STOP: 100,
    MiningState.PERCEPTION_ERROR: 95,
    MiningState.ERROR: 90,
    MiningState.SPIDER_DETECTED: 80,
    MiningState.COMBAT: 80,
    MiningState.MINE_COLLAPSE_DETECTED: 70,
    MiningState.BATTERY_EMPTY: 60,
    MiningState.EQUIPPING_DRILL: 50,
    MiningState.PLAYER_DRAGGED_AWAY: 40,
    MiningState.NOTHING_TO_MINE: 30,
    MiningState.MINING: 10,
    MiningState.OBSERVATION: 5,
    MiningState.IDLE: 0,
}
